---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-pod-only
---
# This service account is used for testing authentication with an incorrect service-account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: other-service-account
---
apiVersion: v1
kind: Pod
metadata:
  name: inventory-pod
  labels:
    app: inventory-pod
spec:
  serviceAccountName: inventory-pod-only
  containers:
  - image: {{INVENTORY_TAG}}
    imagePullPolicy: IfNotPresent
    name: inventory
    command: ["sleep", "infinity"]
  - image: {{INVENTORY_TAG}}
    imagePullPolicy: IfNotPresent
    name: authenticator
    command: ["sleep", "infinity"]
