---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
  - port: 5432
    name: pg-main
  selector:
    app: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: conjur
spec:
  ports:
  - port: 443
    name: https
  - port: 636
    name: ldaps
  selector:
    app: conjur
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres:9.4
        name: postgres
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: conjur
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: conjur
    spec:
      containers:
      - image: us.gcr.io/conjur-gke-dev/conjur:authn-k8s
        name: conjur
        command: ["conjurctl", "server"]
        env:
          - name: CONJUR_APPLIANCE_URL
            value: http://localhost:3000
          - name: DATABASE_URL
            value: postgres://postgres@postgres:5432/postgres
          - name: CONJUR_ADMIN_PASSWORD
            value: admin
          - name: CONJUR_ACCOUNT
            value: cucumber
          - name: CONJUR_DATA_KEY
            value: "{{ DATA_KEY }}"
          - name: RAILS_ENV
            value: test
          - name: CONJUR_AUTHENTICATORS
            value: authn-k8s/minikube
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: conjur-cli
  name: conjur-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conjur-cli
  template:
    metadata:
      labels:
        app: conjur-cli
        name: conjur-cli
    spec:
      containers:
      - name: conjur-cli
        image: cyberark/conjur-cli:5
        imagePullPolicy: Always
        command: ["sleep"]
        args: ["infinity"]
