version: '2'
services:
  docs:
    build:
      context: .
      dockerfile: Dockerfile.docs
    image: conjur-docs
    ports:
      - 4000:4000
      - 4001:4001
    volumes:
      - .:/usr/src
  apidocs:
    build:
      context: ./apidocs
      dockerfile: Dockerfile.apidocs
    image: conjur-apidocs
    ports:
      - 3000:3000
    volumes:
      - ./apidocs/src:/home/node/src
