pg:
  image: postgres:9.3
  
possum:
  image: possum-dev
  environment:
    CONJUR_APPLIANCE_URL: http://localhost:3000
    DATABASE_URL: postgres://postgres@pg/postgres
    POSSUM_ADMIN_PASSWORD: admin
    CONJUR_PASSWORD_ALICE: secret
    POSSUM_DATA_KEY:
    RAILS_ENV:
  volumes:
  - ..:/src/possum
  - ../../conjur-policy-parser:/src/conjur-policy-parser
  links:
  - pg:pg

cucumber:
  image: possum-dev
  entrypoint: bash
  environment:
    CONJUR_APPLIANCE_URL: http://possum:3000
    DATABASE_URL: postgres://postgres@pg/postgres
    POSSUM_ADMIN_PASSWORD: admin
    POSSUM_DATA_KEY:
    RAILS_ENV:
  volumes:
  - ..:/src/possum
  links:
  - possum:possum
  - pg:pg

client:
  image: conjurinc/cli5
  entrypoint: sleep
  command: infinity
  environment:
    CONJUR_APPLIANCE_URL: http://possum:3000
    DATABASE_URL: postgres://postgres@pg/postgres
  links:
  - possum:possum
  volumes:
  - ..:/src/possum
