github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
title: CyberArk Conjur
plugins_dir: ./_plugins
url: https://www.conjur.org
