name: remind review
on:
  push
  # schedule:
  #   - cron:  '*/5 * * * *'
  # workflow_dispatch:

jobs:
  send_pull_requests:
    runs-on: ubuntu-latest
    name: Another test
    steps:
      - name: output
        run: |
          curl -s "$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/pulls?state=open"

# jobs:
#   send_pull_requests:
#     runs-on: ubuntu-latest
#     name: A job to say hello
#     steps:
#       - name: listPullRequests
#         uses: buildsville/list-pull-requests@v1
#         id: list
#         with:
#           token: ${{secrets.GITHUB_TOKEN}}
#           labels: 
#           skip_hour: 99999 # We want to list all of them
#       - name: output
#         run: echo '${{ steps.list.outputs.pulls }}'
